cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <label>Cohort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End</label>
    <type>Date</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>Date</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{000000000}</displayFormat>
        <label>Interview ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohort3/triforciacohort3pack/force-app/main/default/classes/UIcourseController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-27-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class UIcourseController {
    public UIcourseController() {

    }


    @AuraEnabled(cacheable=true)
    public static List<Course__c> retrieve(){

        List<Course__c> multiCourse=New List<Course__c>();
        try {
            multiCourse=[SELECT Id, Name, Cohort__c, End__c, Interview__c, Module__c, Start__c 
            FROM Course__c
            WHERE Start__c>TODAY];
        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return multiCourse;
    }
}