cohort3/triforciacohort3pack/force-app/main/default/objects/Ad__c/Ad__c.object-meta.xml
<CustomObject>
    <label>Ad</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>Advertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <label>Cohort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End</label>
    <type>Date</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Course__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>Date</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{000000000}</displayFormat>
        <label>Interview ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohort3/triforciacohort3pack/force-app/main/default/objects/Lead/fields/Ad__c.field-meta.xml
<CustomField>
    <fullName>Ad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ad</label>
    <referenceTo>Ad__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/objects/Lead/fields/Info_Session_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Info_Session_Date_Time__c</fullName>
    <label>Info Session Date Time</label>
    <type>DateTime</type>
</CustomField>

cohort3/triforciacohort3pack/force-app/main/default/classes/GuestUserController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-28-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class GuestUserController {
    public GuestUserController() {

    }


    @AuraEnabled
    public static string createLead(Lead singleLead, String infoDate){
        // 2023-03-01T20:26:00.000Z
        // yyyy-MM-dd HH:mm:ss

        Datetime info = Datetime.valueOf(infoDate.replace('T',' '));

        singleLead.Info_Session_Date_Time__c=info;

        try {
            insert singleLead;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return singleLead.Id;
    }


    @AuraEnabled(cacheable=true)
    public static Campaign retrieveCampaign(String searchCampaign){
        String search='%'+searchCampaign+'%';
        Campaign singleCampaign = New Campaign();
        try {
            singleCampaign=[SELECT Id,Name FROM Campaign WHERE Name LIKE :search LIMIT 1];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return singleCampaign;
    }


    @AuraEnabled
    public static string createAd(Ad__c singleAd){
        try {
            insert singleAd;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return singleAd.id;
    }


    @AuraEnabled
    public static string createCampaignMember(CampaignMember cm){
        try {
            insert cm;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return cm.id;
    }
    

    @AuraEnabled(cacheable=true)
    public static List<Course__c> retrieveCourse(){

        List<Course__c> multiCourse=New List<Course__c>();
        try {
            // SELECT Id, Name, Cohort__c, End__c, Interview__c, Module__c, Start__c FROM Course__c

            multiCourse=[SELECT Id, Name, Cohort__c, End__c, Interview__c, Module__c, Start__c FROM Course__c
            WHERE Start__c>TODAY];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return multiCourse;
    }
}